django_cms_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.auth import views

from . import views as django_cms_app_views

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile', django_cms_app_views.profile, name='profile'),
    url(r'^signup/$', django_cms_app_views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^doc_types/', include('doc_types.urls', namespace='doc_types')),
    url(r'^', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doc_types/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = "doc_types"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
]

polls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = "polls"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
]

doc_types/models.py
import datetime

from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class Poll(models.Model):
    question = models.CharField(max_length=200)

    def __str__(self):              # Python 3: def __unicode__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):              # Python 3: def __unicode__(self):
        return self.choice_text


class Document(models.Model):
    title = models.CharField(max_length=80)
    # author = ?
    pub_date = models.DateTimeField('publish on')

    class Meta:
        abstract = True


class HowTo(Document):
    intro = models.CharField(max_length=500)
    tags = TaggableManager()

    def __str__(self):
        return '(title:"' + self.title + '"), (' + 'intro:"' + self.intro + '")'


class Step(models.Model):
    how_to = models.ForeignKey(HowTo, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    markdown_content = models.CharField(max_length=5000) # chang the length


# class TheoreticalArticle(models.Model):
#     pass

django_cms_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

django_cms_app/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, render, redirect

from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def profile(request):
    return render(request, 'profile.html')

doc_types/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Choice, Poll
from .models import HowTo, Step


class IndexView(generic.ListView):
    template_name = 'doc_types/index.html'
    context_object_name = 'howto_list'

    def get_queryset(self):
        return HowTo.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = HowTo
    template_name = 'doc_types/detail.html'
    context_object_name = 'current_how_to'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'doc_types/results.html'


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'doc_types/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('doc_types:results', args=(p.id,)))

polls/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Choice, Poll
from .models import HowTo, Step


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'howto_list'

    def get_queryset(self):
        return HowTo.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = HowTo
    template_name = 'polls/detail.html'
    context_object_name = 'current_how_to'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

doc_types/templates/doc_types/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ current_how_to.title }}</h1>
  <p>{{ current_how_to.pub_date }}</p>
  <p>{{ current_how_to.intro }}</p>

  {% for step in current_how_to.step_set.all reversed %}
    <div class="step">
      <div class="stepicon">{{ forloop.counter }}</div>
      <h2>{{ step.title }}</h2>
      <p>{{ step.markdown_content }}</p>
    </div>
  {% endfor %}
{% endblock %}

doc_types/templates/doc_types/index.html
{% extends 'base.html' %}

{% block content %}
<h1>How-tos</h1>
{% if howto_list %}

    {% for how_to in howto_list %}
    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-header">Header</div>
      <div class="card-body">
        <h5 class="card-title">
          <a href="{% url 'doc_types:detail' how_to.id %}">{{ how_to.title }}</a>
        </h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </div>
    {% endfor %}

{% else %}
    <p>No how_tos are available.</p>
{% endif %}
{% endblock %}

doc_types/templates/doc_types/results.html
{% extends 'doc_types/base.html' %}

{% block content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'doc_types:detail' poll.id %}">Vote again?</a>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<h1>How-tos</h1>
{% if howto_list %}
    <ul>
    {% for how_to in howto_list %}
		<li><a href="{% url 'polls:detail' how_to.id %}">{{ how_to.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No how_tos are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
{% endblock %}

templates/base.html
{% load cms_tags menu_tags sekizai_tags staticfiles %}
<!DOCTYPE html>
<!-- change to {{ LANGUAGE_CODE }} -->
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% page_attribute 'meta_description' %}">
    <meta name="author" content="">

    <title>{% page_attribute 'page_title' %} | RedLab</title>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">





    <!-- Bootstrap Core CSS -->
    <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <!-- BOOTSTRAP CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"> -->

    <!-- Custom CSS -->
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Merriweather:700" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% render_block "css" %}
  </head>

  <body>
    <!-- cms_toolbar must be at beginning of body -->
    {% cms_toolbar %}

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2d3136;">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span class="nav-logo">RedLab!</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto nav-item">

            {% show_menu 0 100 100 100 "menu/menu.html" %}

            {% if user.is_authenticated %}
            <!-- <li class="nav-item"><a href="{% url 'profile'%}">Profile: {{ user.get_username }}</a></li> -->
            <li class="nav-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <!-- <li class="nav-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li> -->
            <!-- <li class="nav-item"><a href="{% url 'signup'%}?next={{request.path}}">Signup</a></li> -->
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- BREADCRUMB -->
      <div class="row">
        <div class="col-lg-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">{% page_attribute 'page_title' %}</li>
            </ol>
          </nav>
        </div>
      </div>

      <!-- CURRENT PAGE CONTENT -->
      <div class="row">
        <div class="col-lg-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>

      <hr>

      <!-- FOOTER -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            {% static_placeholder "footer" %}
          </div>
        </div>
      </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    <!-- LOCAL JS -->
    {% render_block "js" %}
  </body>

</html>

templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "feature" %}
	{% placeholder "content" %}
	{% placeholder "splashbox" %}
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <div class="col-sm">
    <h1>We are glad you are here, {{ user.first_name }} {{ user.last_name }}!</h1>
    <p>Username: {{ user.get_username }}</p>
    <p>Email: {{ user.email }}</p>
  </div>
  <div class="col-sm">
    <img id="profile_icon" src="{% static "django_cms_app/profile_icon.png" %}" alt="profile_icon">
    <a class="btn btn-primary btn-lg" href="#" role="button">Edit</a>
  </div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}